import pandas as pd

df=pd.read_csv("movie.csv")
print(df)
print(df.head(2))
print("\n")
print(df.rating.min())
print("\n")
print(df[df.genre=="Action"])
print("_________")
print(df.genre.value_counts())
print("-----")
print(df[["title","genre"]])
print("____")
print(df[(df.release_year>2014)&(df.duration_minutes<150)])
print("----")
print(df.describe())
df["age"] = df["release_year"].apply(lambda x : 2026-x)
print(df)